# --- !Ups

CREATE TABLE USER_MAP_SETTINGS (
  ID                BIGINT NOT NULL AUTO_INCREMENT,
  USER_ID           BIGINT NOT NULL,
  CENTER_LATITUDE   DOUBLE NOT NULL,
  CENTER_LONGITUDE  DOUBLE NOT NULL,
  CONSTRAINT        UMSETTINGS_USER_UC
    UNIQUE            (USER_ID),
  CONSTRAINT        UMSETTINGS_USER_FK
    FOREIGN KEY       (USER_ID)
    REFERENCES        USER (ID),
  PRIMARY KEY       (ID)
);

# --- !Downs

SET UNIQUE_CHECKS = 0;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS USER_MAP_SETTINGS;
SET FOREIGN_KEY_CHECKS = 1;
SET UNIQUE_CHECKS = 1;
